### ISSUE TITLE
UnboundLocalError: local variable 'IndexError' referenced before assignment

### ISSUE THREAD

**Issue by mbfhunzaker** [unitedstates/congressional-record#16]
Hey! I tried to scrape data for the date `1994-02-22` and I bumped into the following error:

```
UnboundLocalError: local variable 'IndexError' referenced before assignment
```

Do you have any ideas why this might occur?

**Comment by nclarkjudd** [comment]
Hi! I have taken over as the lead maintainer for this repository, and changes I've made to improve usability and performance have broken backwards compatibility. If you're still using this software, you should give the latest commit a try to see if this issue persists.
