### ISSUE TITLE
Having Trouble Structuring Request Command

### ISSUE THREAD

**Issue by rogerskmc** [unitedstates/congressional-record#25]
**From 8/24/2017:**
I am a complete novice trying to figure out how to use GitHub and Python for a research project, and I am hoping that someone will take pity on me and help me out…
 
I cloned the repository and have it in GitHub Desktop. From there, I opened it in Terminal, typed “python -m congressionalrecord.cli –h” for instructions, and then tried to request speeches between Jan 3, 2015 and Jan 3, 2017 using the following command (to try and save the result to a folder on my desktop):
 
python -m “congressionalrecord.cli” -od /Users/Kathleen/Desktop/floor 2015-01-03:2017-01-03 json
 
I tried changing this command around a few different ways and got different errors. What would a correct command look like? And/or what might I be doing wrong?

**EDIT (8/30/2017):** 
I believe I actually should be using the pg option, rather than json, to produce CSV files. When I use "python -m congressionalrecord.cli 2015-01-03 2017-01-03 pg", I get an error message: IOError: [Errno2] No such file or directory" 'dbfiles/pages.csv'

Should I be adding a file destination to the request? I tried adding "/Users/Kathleen/Desktop/floor" to different places in the command to no avail.

**Comment by nclarkjudd** [comment]
try creating the directory "dbfiles" in the repository root.
Alternatively, you can use the --csvpath argument as described in the help file to specify an output path for CSV files.
