### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'congressionalrecord' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by atnjqt** [unitedstates/congressional-record#44]
```
$ git clone https://github.com/unitedstates/congressional-record.git

$ cd congressional-record/

$ python -m congressionalrecord.cli -h
```
Running these steps yields the following error: **pkg_resources.DistributionNotFound: The 'congressionalrecord' distribution was not found and is required by the application**

I'm running on MacOS 10.15 Catalina, I'm guessing this is a dependency issue... I see what looks like a yaml file w/ requirements.txt for a docker build but it's unclear if that is the case.

Just interested in testing out this congressional getter, thanks!

**Comment by AlJohri** [comment]
@atnjqt you need to install the package before running it. here are the commands to install and use the package within a virtualenv:

```bash
git clone https://github.com/unitedstates/congressional-record.git
cd congressional-record
python3 -m venv .venv
.venv/bin/python -m pip install -e .
.venv/bin/python -m congressionalrecord.cli -h
```

**Comment by nclarkjudd** [comment]
Assuming @AlJohri's instructions work for `venv` (I am still a virtualenv/virtualenvwrapper guy), added to README for other users

**Comment by atnjqt** [comment]
Thanks for the updated README! Those steps, in addition to downloading PostgreSQL for MacOS, allows me to at least run the congressionalrecord.cli!
